// Kiểm thử các game/tiện ích mới: mở, thao tác cơ bản, kiểm tra không lỗi JS.
const ROOT = require('path').resolve(__dirname, '..', '..');
const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch(), errs = [], out = [];
  const p = await (await b.newContext({ viewport: { width: 430, height: 900 } })).newPage();
  p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && !/ERR_|Failed to load/.test(m.text()) && errs.push(m.text()));
  const open = async id => { await p.goto('file://' + ROOT + '/index.html#/' + id); await p.waitForTimeout(350); };
  const log = (n, v) => out.push(n + ': ' + v);
  const nonBlank = async () => p.evaluate(() => { const c = document.querySelector('canvas'); if (!c) return 'no-canvas'; const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data; let k = 0; for (let i = 0; i < d.length; i += 400) if (d[i] > 40 || d[i + 1] > 40 || d[i + 2] > 40) k++; return k; });

  await open('game/pong2'); await p.keyboard.down('w'); await p.waitForTimeout(500); await p.keyboard.up('w'); log('pong2 canvas px', await nonBlank());
  await open('game/goldminer'); await p.keyboard.press(' '); await p.waitForTimeout(1500); log('goldminer canvas px', await nonBlank());
  await open('game/racing'); await p.keyboard.press('ArrowLeft'); await p.waitForTimeout(1200); log('racing canvas px', await nonBlank());
  await open('game/zombie'); await p.waitForTimeout(2500); await p.locator('canvas').click({ position: { x: 200, y: 150 } }); log('zombie canvas px', await nonBlank());
  await open('game/penalty'); await p.keyboard.press(' '); await p.waitForTimeout(300); await p.keyboard.press(' '); await p.waitForTimeout(1500); log('penalty msg', await p.locator('.msg').innerText());
  await open('game/archery'); await p.locator('canvas').click({ position: { x: 100, y: 180 } }); log('archery msg', await p.locator('.msg').innerText());
  await open('game/mathrush'); const t = await p.locator('.q').innerText(); await p.locator('.opts button').first().click(); log('mathrush q', t + ' | score ' + await p.locator('.sc').innerText());
  await open('game/maze'); await p.keyboard.press('ArrowRight'); await p.keyboard.press('ArrowDown'); log('maze canvas px', await nonBlank());
  await open('game/candyman'); await p.keyboard.press('ArrowLeft'); await p.waitForTimeout(900); log('candyman score', await p.locator('.sc').innerText());
  await open('game/colornum'); const first = p.locator('.cn [data-p]').first(); const num = await first.getAttribute('data-c'); await p.locator(`.pal [data-k="${num}"]`).click(); await first.click(); log('colornum pc', await p.locator('.pc').innerText());
  await open('game/farm'); await p.evaluate(() => localStorage.removeItem('gv_farm')); await open('game/farm'); await p.locator('.fm [data-i]').first().click(); log('farm coins', await p.locator('.co').innerText());
  await open('game/bakery'); const want = await p.locator('.want').innerText(); log('bakery want', want); await p.locator('.ing button').first().click(); log('bakery msg', await p.locator('.msg').innerText());
  const dragc = async (sel, a, bb) => { const bx = await p.locator(sel).boundingBox(), sc = bx.width / (await p.evaluate(s => document.querySelector(s).width, sel)); await p.mouse.move(bx.x + a[0] * sc, bx.y + a[1] * sc); await p.mouse.down(); await p.mouse.move(bx.x + bb[0] * sc, bx.y + bb[1] * sc, { steps: 5 }); await p.mouse.up(); };
  await open('game/basketball'); await dragc('canvas', [200, 200], [140, 270]); await p.waitForTimeout(1500); log('basketball', (await p.locator('.msg').innerText()) + ' | bóng còn ' + await p.locator('.bl').innerText());
  await open('game/billiards'); await dragc('canvas', [200, 135], [130, 135]); await p.waitForTimeout(1500); log('billiards shots', await p.locator('.sc').innerText() + ' | px ' + await nonBlank());
  await open('game/bowling'); await dragc('canvas', [150, 300], [150, 380]); await p.waitForTimeout(4500); log('bowling', (await p.locator('.msg').innerText()) + ' | điểm ' + await p.locator('.sc').innerText());
  await open('game/lixi'); await p.keyboard.down('ArrowLeft'); await p.waitForTimeout(1500); await p.keyboard.up('ArrowLeft'); log('lixi canvas px', await nonBlank());
  await open('game/baucua'); await p.locator('.bd [data-k]').first().click(); await p.click('.roll'); await p.waitForTimeout(1900); log('baucua', (await p.locator('.msg').innerText()) + ' | xu ' + await p.locator('.sc').innerText());
  await open('game/lovematch'); await p.locator('.lm [data-i]').nth(0).click(); await p.locator('.lm [data-i]').nth(1).click(); log('lovematch lượt', await p.locator('.sc').innerText());
  await open('game/santa'); await p.keyboard.press(' '); await p.waitForTimeout(1500); log('santa canvas px', await nonBlank());
  await open('game/halloween'); await p.keyboard.down('ArrowRight'); await p.waitForTimeout(1200); await p.keyboard.up('ArrowRight'); log('halloween score', await p.locator('.sc').innerText() + ' | px ' + await nonBlank());
  await open('game/tank2'); await p.keyboard.down('d'); await p.keyboard.press(' '); await p.waitForTimeout(900); await p.keyboard.up('d'); log('tank2 px', await nonBlank());
  await open('game/sniper'); await p.locator('canvas').click({ position: { x: 120, y: 100 } }); await p.waitForTimeout(600); log('sniper ammo', await p.locator('.am').innerText() + ' | px ' + await nonBlank());
  await open('game/airfight'); await p.keyboard.down('ArrowLeft'); await p.waitForTimeout(1500); await p.keyboard.up('ArrowLeft'); log('airfight px', await nonBlank());
  await open('game/towerdef'); await p.locator('canvas').click({ position: { x: 200, y: 20 } }); log('towerdef xu', await p.locator('.co').innerText()); await p.click('.nw'); await p.waitForTimeout(1500); log('towerdef wave', await p.locator('.sc').innerText());
  await open('game/fishing'); const fb = await p.locator('canvas').boundingBox(); await p.mouse.move(fb.x + 150, fb.y + 100); await p.mouse.down(); await p.waitForTimeout(900); await p.mouse.up(); await p.waitForTimeout(600); log('fishing px', await nonBlank());
  await open('game/stickrun'); await p.keyboard.press(' '); await p.waitForTimeout(1200); log('stickrun score', await p.locator('.sc').innerText() + ' | px ' + await nonBlank());
  await open('game/bomber'); await p.keyboard.press(' '); await p.keyboard.down('ArrowDown'); await p.waitForTimeout(500); await p.keyboard.up('ArrowDown'); await p.waitForTimeout(2300); log('bomber', (await p.locator('.msg').innerText()) + ' | px ' + await nonBlank());
  await open('game/haunted'); await p.keyboard.press('ArrowRight'); await p.keyboard.press('ArrowDown'); await p.waitForTimeout(800); log('haunted px', await nonBlank());
  await open('game/vocabquiz'); await p.locator('.opts button').first().click(); log('vocabquiz', await p.locator('.msg').innerText() + ' | ' + await p.locator('.sc').innerText());
  await open('game/wordscramble'); await p.locator('.lt button').first().click(); log('wordscramble hint', await p.locator('.mn').innerText() + ' | picked ' + await p.locator('.ans button').count());
  await open('game/freedraw'); await dragc('canvas', [100, 100], [200, 200]); log('freedraw ok', await p.evaluate(() => { const c = document.querySelector('canvas'); const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data; let k = 0; for (let i = 0; i < d.length; i += 4) if (d[i] < 200) k++; return k; }));
  await open('game/dressup'); await p.locator('[data-e="👑"]').click(); await p.click('.rn'); log('dressup', (await p.locator('.dv').innerText()).replace(/\s+/g, ' '));
  await open('game/cooking'); await p.waitForTimeout(1800); await p.locator('.pan').first().click(); log('cooking', await p.locator('.sc').innerText() + ' | ' + await p.locator('.msg').innerText());
  await open('game/iqtest'); await p.locator('.opts button').first().click(); log('iqtest q', (await p.locator('.q').innerText()).slice(0, 40));
  await open('tool/expense'); await p.fill('.am', '50000'); await p.click('.add'); log('expense summary', (await p.locator('.sm').innerText()).replace(/\s+/g, ' '));
  await open('tool/habit'); await p.fill('.nm', 'Uống nước'); await p.click('.add'); await p.locator('.xt [data-t]:not([disabled])').first().click(); log('habit streak', (await p.locator('.ls .it span[title]').first().innerText()));
  await open('tool/loan'); log('loan out', (await p.locator('.out').innerText()).replace(/\s+/g, ' ').slice(0, 110)); await p.click('[data-m=save]'); log('save out', (await p.locator('.out').innerText()).replace(/\s+/g, ' ').slice(0, 90));
  await open('tool/metronome'); await p.click('.go'); await p.waitForTimeout(700); log('metronome btn', await p.locator('.go').innerText()); await p.click('.go');
  console.log(out.join('\n')); console.log(errs.join('\n') || 'no errors'); await b.close();
})();
